# Generated by Django 4.2.6 on 2025-11-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipe_casecost_recipe_caseweightlb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutemplate',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menutemplate',
            name='sections',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menutemplate',
            name='template_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menutemplate',
            name='warning_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menutemplate',
            name='global_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menutemplate',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
