# Generated by Django 4.2.6 on 2025-11-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_menutemplate_format_menutemplate_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutemplate',
            name='offer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
